#%RAML 1.0 NamedExample
[
  {
                "customerName" : "ravi",
                "bank": "HDFC",
                "type": "savings",
                "branchName" :"BLR",
                "accountNum": "54326781234",
                "ifscCode": "HDFC10034",
                "mailId" : "ravi@gmail.com",
                "cardStatus" : "Locked"
              },
              {
                "customerName" : "Sreekanth",
                "bank": "HDFC",
                "type": "savings",
                "branchName" :"BLR",
                "accountNum": "5432678234",
                "ifscCode": "HDFC10034",
                "mailId" : "srikanth@gmail.com",
                "cardStatus" : "Locked"
              }
]