#%RAML 1.0 NamedExample
{
            "user": "admin",
            "password": "admin",
            "accountNum": "1234567892",
            "bank": "HDFC",
            "acctStatus": "Unlock"
          }